### ISSUE TITLE
Consider adding a C compatibility header

### ISSUE THREAD

**Issue by beqabeqa473** [NSoiffer/MathCATForC#3]
For now, generated header is not compatible with C.

Please consider adding a C-header to be included in C projects

Thanks.

**Comment by NSoiffer** [comment]
Thanks for mentioning that. I hadn't noticed it wasn't compatible with C. I've started to look into what it takes to get C headers and C++ headers generated automatically. My first attempt failed, but I'll do some more reading.

**Comment by NSoiffer** [comment]
This is now done and included in the [lastest release](https://github.com/NSoiffer/MathCATForC/releases/tag/V0.5.1).
